[new module] azure-hosting-webapp
codecampn/terraform-modules pull request #7
Opened 2020-09-30 13:59 UTC by maxhaensel

create a new module to host a webapp on azure

2020-10-08 11:19 UTC, coc-pi approved these changes

2020-10-08 11:20 UTC, coc-pi reviewed
Können die Dinge, die AWS hier handelt nicht auch über Azure geregelt werden? Andersrum gefragt, für was genau brauchen wir hier die AWS entries?

2020-10-08 11:33 UTC, pascal-sochacki requested changes
Ich glaub die gesamte ReadMe muss noch angepasst werden oder?

2020-10-08 11:33 UTC, pascal-sochacki commented on azure/hosting-webapp/README.md
> +| location             | The name of the function as configured in AWS Lambda                             | "auth-function-tf" |
Ist die description nicht falsch?

2020-11-26 14:57 UTC, maxhaensel commented on azure/hosting-webapp/README.md
> +| location             | The name of the function as configured in AWS Lambda                             | "auth-function-tf" |
OH yes! danke

2024-06-13 19:29 UTC, closed without merging